config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      patch 'editor_switch' # 編集権限切替
    end
    collection do
      post 'import'
    end
  end
  resources :repairs do
    member do
      get 'show_sub'
      get 'edit_progress' # 進捗チェック
      patch 'update_progress'
      patch 'update_contacted' # 連絡チェック
      patch 'update_delivery' # 引渡チェック
      patch 'update_reminder' # 催促チェック
    end
    collection do
      get 'export'
      get 'export_pdf'
      get 'data_management'
      post 'import'
      get 'delete_check' # まとめて削除チェック
      patch 'update_delete_check' # まとめて削除チェック更新
      get 'delete_confirmation' # まとめて削除確認
      delete 'delete_all' # まとめて削除
      patch 'reset_delete_check' # 削除選択のリセット
    end
  end
  resources :machine_categories, except: :show do
    collection do
      post 'import'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 4 }, allow_nil: true

  def User.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def self.import(file)
    imported_num = 0

    open(file.path, 'r:cp932:utf-8', undef: :replace) do |f|
      csv = CSV.new(f, :headers => :first_row)
      begin
        csv.each do |row|
          next if row.header_row?
          table = Hash[[row.headers, row.fields].transpose]

          user = find_by(id: table["id"])
          if user.nil?
            user = new
          end

          user.attributes = table.to_hash.slice(*table.to_hash.except(:id).keys)

          if user.valid?
            user.save!
            imported_num += 1
          end
        end
      rescue
      end
    end
    imported_num
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user, only: %i(index new create edit update destroy import)
  before_action :correct_or_admin_user, only: %i(show editor_switch)
  before_action :set_user, only: %i(show edit update editor_switch destroy)

  def index
    @users_all = User.all
    @users = User.paginate(page: params[:page], per_page: 15).order(id: :ASC)

    # CSVF出力
    respond_to do |format|
      format.html
      format.csv do
        if current_user.admin?
          send_data render_to_string.encode(Encoding::Windows_31J, undef: :replace, row_sep: "\r\n", force_quotes: true),
          filename: "ユーザ一覧(#{DateTime.current&.strftime("%Y年%-m月%-d日%-H時%-M分現在")}).csv", type: :csv
        else
          redirect_to repairs_url
        end
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "新規ユーザー(#{@user.name})を作成しました。"
      redirect_to users_url
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "#{@user.name}の情報を更新しました。"
      redirect_to users_url
    else
      render :edit
    end
  end

  def editor_switch
    if @user.update_attributes!(editor_params)
      flash[:success] = "#{@user.name}の編集権限を変更しました。"
      redirect_to @user
    end
  end

  def destroy
    @user.destroy
    flash[:danger] = "#{@user.name}のユーザー情報を削除しました。"
    redirect_to users_url
  end

  def import
    if params[:users_file].blank?
      flash[:danger] = "インポートするCSVファイルを選択してください。"
      redirect_to data_management_repairs_url
    else
      num = User.import(params[:users_file])
      if num > 0
        flash[:success] = "#{num.to_s}件の情報を追加/更新しました。"
        redirect_to users_url
      else
        flash[:danger] = "読み込みエラーが発生しました。フォーマットを確認してください。"
        redirect_to data_management_repairs_url
      end
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def editor_params
      params.require(:user).permit(:editor)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render partial: 'shared/error_messages', locals: { obj: @user } %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <div class="center">
    <%= f.submit yield(:button_text), class: "btn btn-primary btn-lg btn-#{yield(:class_text)}" %>
    <%= link_to "戻る", users_path, class: "btn btn-secondary btn-lg btn-#{yield(:class_text)}" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー情報更新") %>
<% provide(:class_text, "user--edit") %>
<% provide(:button_text, "更新") %>
<h1>ユーザー情報更新</h1>
<div class="row justify-content-md-center">
  <div class="col col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>
<h1>ユーザー一覧</h1>
<div class="">
  <%= link_to "ユーザー登録", signup_path, class: "btn btn-primary btn-user--new" %>
</div>
<div>
  <%= will_paginate @users, previous_label: '<', next_label: '>', inner_window: 1 %>
  <table class="table table-bordered table-condensed center id="table-users"">
    <thead class="thead-light">
      <tr>
        <% if current_user.admin? %>
          <th width="90"></th>
        <% end %>
        <th><%= User.human_attribute_name :name %></th>
        <th><%= User.human_attribute_name :email %></th>
        <% if current_user.admin %>
          <th width="90"></th>
        <% end %>
      </tr>
    </thead>
    <% @users.each do |user| %>
      <% unless user.admin && !current_user.admin? %>
        <tbody>
          <tr>
            <% if current_user.admin? %>
              <td><%= link_to "編集", edit_user_path(user), class: "btn btn-success" %></td>
            <% end %>
            <td>
              <% if current_user.admin? || current_user == user %>
                <%= link_to user.name, user %>
              <% else %>
                <%= user.name %>
              <% end %>
              <% if user.created_at.since(1.day) > Time.now %>
                <span class="badge badge-pill badge-info badge-new">
                  new
                </span>
              <% end %>
              <% if user.updated_at.since(2.minutes) > Time.now %>
                <span class="badge badge-pill badge-info badge-update">
                  update
                </span>
              <% end %>
            </td>
            <td><%= user.email %></td>
            <% if current_user.admin? %>
              <td>
                <% if current_user.admin? && !current_user?(user) %>
                  <%= link_to "削除", user, method: :delete, data: { confirm: "#{user.name}のデータを削除します。",
                      verify: "#{user.name}", verify_text: "削除するユーザー名を入力してください",
                      cancel: "やめる", commit: "削除する"}, title: "削除の確認", class: "btn btn-danger"%>
                <% end %>
              </td>
            <% end %>
          </tr>
        </tbody>
      <% end %>
    <% end %>
  </table>
  <%= will_paginate @users, previous_label: '<', next_label: '>', inner_window: 1 %>
</div>

<link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">

app/views/users/new.html.erb
<% provide(:title, "ユーザー登録") %>
<% provide(:class_text, "signup") %>
<% provide(:button_text, "新規登録") %>
<h1>ユーザー登録</h1>
<div class="row justify-content-md-center">
  <div class="col col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% provide(:class_text, "user--edit") %>
<% provide(:button_text, "変更") %>
<h1>ユーザー情報</h1>
<div class="row justify-content-md-center">
  <div class="<div class="col col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: editor_switch_user_path(@user), local: true, method: :patch) do |f| %>
      <div class="center">
        <h4><%= @user.name %></h4>
        <h5><%= @user.email %></h5>
        <% unless current_user.admin? && current_user?(@user) %>
          <div class="editor-form">
            <h2>編集権限</h2>
            <div class="editor-btn-group">
              <%= f.label "有", class: "editor-btn" %>
              <%= f.radio_button :editor, true %>
              &emsp;&emsp;
              <%= f.label "無", class: "editor-btn" %>
              <%= f.radio_button :editor, false %>
            </div>
            <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>