config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      patch 'editor_switch' # 編集権限切替
    end
    collection do
      post 'import'
    end
  end
  resources :repairs do
    member do
      get 'show_sub'
      get 'edit_progress' # 進捗チェック
      patch 'update_progress'
      patch 'update_contacted' # 連絡チェック
      patch 'update_delivery' # 引渡チェック
      patch 'update_reminder' # 催促チェック
    end
    collection do
      get 'export'
      get 'export_pdf'
      get 'data_management'
      post 'import'
      get 'delete_check' # まとめて削除チェック
      patch 'update_delete_check' # まとめて削除チェック更新
      get 'delete_confirmation' # まとめて削除確認
      delete 'delete_all' # まとめて削除
      patch 'reset_delete_check' # 削除選択のリセット
    end
  end
  resources :machine_categories, except: :show do
    collection do
      post 'import'
    end
  end
end

app/models/machine_category.rb
class MachineCategory < ApplicationRecord
  validates :code, presence: true, inclusion: {in: 1..9999 }, uniqueness: true
  validates :product, presence: true, length: { minimum: 1, maximum: 15 }

  def self.import(file)
    imported_num = 0

    open(file.path, 'r:cp932:utf-8', undef: :replace) do |f|
      csv = CSV.new(f, :headers => :first_row)
      begin
        csv.each do |row|
          next if row.header_row?
          table = Hash[[row.headers, row.fields].transpose]

          machine_category = find_by(id: table["id"])
          if machine_category.nil?
            machine_category = new
          end

          machine_category.attributes = table.to_hash.slice(*table.to_hash.except(:id).keys)

          if machine_category.valid?
            machine_category.save!
            imported_num += 1
          end
        end
      rescue
      end
    end
    imported_num
  end
end

app/controllers/machine_categories_controller.rb
class MachineCategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user
  before_action :set_machine_category, only: %i(edit update destroy)

  def index
    @machine_categories_all = MachineCategory.all
    @machine_categories = MachineCategory.all.order(code: :ASC)

    # CSVF出力
    respond_to do |format|
      format.html
      format.csv do
        if current_user.admin?
          send_data render_to_string.encode(Encoding::Windows_31J, undef: :replace, row_sep: "\r\n", force_quotes: true),
          filename: "製品カテゴリ一覧(#{DateTime.current&.strftime("%Y年%-m月%-d日%-H時%-M分現在")}).csv", type: :csv
        else
          redirect_to repairs_url
        end
      end
    end
  end

  def new
    @machine_category = MachineCategory.new
  end

  def create
    @machine_category = MachineCategory.new(machine_category_params)
    if @machine_category.save
      flash[:success] = "製品種目「#{@machine_category.product}」を登録しました。"
      redirect_to machine_categories_url
    else
      flash[:danger] = @machine_category.errors.full_messages.join("<br>").html_safe
      redirect_to machine_categories_url
    end
  end

  def edit
  end

  def update
    if @machine_category.update_attributes(machine_category_params)
      flash[:success] = "「#{@machine_category.product}」の情報を更新しました。"
      redirect_to machine_categories_url
    else
      flash[:danger] = @machine_category.errors.full_messages.join("<br>").html_safe
      redirect_to machine_categories_url
    end
  end

  def destroy
    @machine_category.destroy
    flash[:danger] = "「#{@machine_category.product}」を削除しました。"
    redirect_to machine_categories_url
  end

  def import
    if params[:machine_categories_file].blank?
      flash[:danger] = "インポートするCSVファイルを選択してください。"
      redirect_to data_management_repairs_url
    else
      num = MachineCategory.import(params[:machine_categories_file])
      if num > 0
        flash[:success] = "#{num.to_s}件の情報を追加/更新しました。"
        redirect_to machine_categories_url
      else
        flash[:danger] = "読み込みエラーが発生しました。フォーマットを確認してください。"
        redirect_to data_management_repairs_url
      end
    end
  end

  private

    def machine_category_params
      params.require(:machine_category).permit(:code, :product)
    end
end

app/helpers/machine_categories_helper.rb
module MachineCategoriesHelper
end

app/views/machine_categories/_edit.html.erb
<% provide(:class_text, "edit") %>
<% provide(:button_text, "更新") %>
<div class="modal-dialog modal-md modal-dialog-centered">
  <div class="modal-content">
    <div class="col-md-12">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row justify-content-md-center">
        <div class="col-md-8 col-offset-2">
          <h1>製品種目編集</h1>
          <%= render 'from' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/machine_categories/_from.html.erb
<%= form_with(model: @machine_category, local: true) do |f| %>
  <%= render partial: 'shared/error_messages', locals: { obj: @machine_category } %>

  <%= f.label :code, class: "label-#{yield(:class_text)}" %>
  <%= f.number_field :code, class: "form-control" %>

  <%= f.label :product, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :product, class: "form-control" %>

  <div class="center">
    <%= f.submit yield(:button_text), class: "btn btn-primary btn-lg btn-#{yield(:class_text)}" %>
  </div>
<% end %>

app/views/machine_categories/_new.html.erb
<% provide(:class_text, "new") %>
<% provide(:button_text, "新規登録") %>
<div class="modal-dialog modal-md modal-dialog-centered">
  <div class="modal-content">
    <div class="col-md-12">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row justify-content-md-center">
        <div class="col-md-8 col-offset-2">
          <h1>製品種目登録</h1>
          <%= render 'from' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/machine_categories/edit.js.erb
$("#edit").html("<%= escape_javascript(render 'edit') %>");
$("#edit").modal("show");

app/views/machine_categories/index.html.erb
<% provide(:title, "製品種目一覧") %>
<h1>製品種目一覧</h1>
<div class="row justify-content-md-center">
  <div class="col-md-6 offset-col-3">
    <%= link_to "新規登録", new_machine_category_path, remote: true, class: "btn btn-primary btn-repair--new" %>
    <table class="table table-bordered table-condensed table-hover table-category-index center">
      <thead class="thead-light">
        <tr>
          <th width="100"></th>
          <th><%= MachineCategory.human_attribute_name :code %></th>
          <th><%= MachineCategory.human_attribute_name :product %></th>
          <% if current_user.admin? %>
            <th></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @machine_categories.each do |m| %>
          <tr>
            <td><%= link_to "編集", edit_machine_category_path(m), remote: true, class: "btn btn-sm btn-success" %></td>
            <td><%= format('%04d', m.code) %></td>
            <td>
              <%= m.product %>
              <% if m.created_at.since(1.day) > Time.now %>
                <span class="badge badge-pill badge-info badge-new">
                  new
                </span>
              <% end %>
              <% if m.updated_at.since(3.second) > Time.now %>
                <span class="badge badge-pill badge-info badge-update">
                  update
                </span>
              <% end %>
            </td>
            <% if current_user.admin? %>
              <td>
                <%= link_to "削除", m, method: :delete, data: { confirm: "「#{m.product}」を削除します。",
                    cancel: "やめる", commit: "削除する"}, title: "削除の確認", class: "btn btn-sm btn-danger" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<!-- モーダル -->
<div id="new" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/machine_categories/new.js.erb
$("#new").html("<%= escape_javascript(render 'new') %>");
$("#new").modal("show");

app/views/machine_categories/update.html.erb
<h1>MachineCategory#update</h1>
<p>Find me in app/views/machine_category/update.html.erb</p>