config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      patch 'editor_switch' # 編集権限切替
    end
    collection do
      post 'import'
    end
  end
  resources :repairs do
    member do
      get 'show_sub'
      get 'edit_progress' # 進捗チェック
      patch 'update_progress'
      patch 'update_contacted' # 連絡チェック
      patch 'update_delivery' # 引渡チェック
      patch 'update_reminder' # 催促チェック
    end
    collection do
      get 'export'
      get 'export_pdf'
      get 'data_management'
      post 'import'
      get 'delete_check' # まとめて削除チェック
      patch 'update_delete_check' # まとめて削除チェック更新
      get 'delete_confirmation' # まとめて削除確認
      delete 'delete_all' # まとめて削除
      patch 'reset_delete_check' # 削除選択のリセット
    end
  end
  resources :machine_categories, except: :show do
    collection do
      post 'import'
    end
  end
end

app/models/repair.rb
class Repair < ApplicationRecord
  validates :reception_day, presence: true
  validates :customer_name, presence: true, length: { maximum: 50 }
  validates :address, length: { maximum: 100 }
  validates :phone_number, format: { with: /\A\d{10}\z/ }, allow_blank: true
  validates :mobile_phone_number, format: { with: /\A\d{10,11}\z/ }, allow_blank: true
  validates :machine_model, length: { maximum: 30 }
  validates :condition, length: { maximum: 500 }
  validates :category, length: { maximum: 30 }
  validates :progress,presence: true, length: { maximum: 1 }
  validates :repair_staff, length: { maximum: 50 }
  validates :note, length: { maximum: 500 }
  validates :repair_staff, length: { maximum: 50 }
  validates :contacted, presence: true, length: { maximum: 1 }
  validates :delivery, presence: true, length: { maximum: 1 }
  validates :reminder, presence: true, length: { maximum: 1 }

  # 引渡済と催促有の同時登録は無効
  validate :reminder_is_invalid_if_delivered

  # 引渡済と修理中の同時登録は無効
  validate :in_progress_is_invalid_if_delivered

  # 引渡済と完了の同時登録は無効
  validate :no_progress_is_invalid_if_delivered

  def reminder_is_invalid_if_delivered
    errors.add(:reminder, "有と引渡済は同時に登録できません。催促を解除してください。") if delivery == 2 && reminder == 2
  end

  def in_progress_is_invalid_if_delivered
    errors.add(:delivery, "済と修理中は同時に登録できません。先に完了登録をしてください。") if delivery == 2 && progress == 2
  end

  def no_progress_is_invalid_if_delivered
    errors.add(:delivery, "済と未完了は同時に登録できません。先に完了登録をしてください。") if delivery == 2 && progress == 1
  end

  scope :reception_day_between, -> from, to {
    if from.present? && to.present?
      where(reception_day: from..to)
    elsif from.present?
      where('reception_day >= ?', from)
    elsif to.present?
      where('reception_day <= ?', to)
    end
  }

  scope :search, -> (search_params) do
    return if search_params.blank?

    customer_name_like(search_params[:customer_name]).
    reception_day_from((search_params[:reception_day_from].to_date)&.yesterday). # 空の値で検索するとyesterdayがnilとなりエラーになるので、&.(ぼっち演算子)でnilのエラーを返さないようにする
    reception_day_to(search_params[:reception_day_to])
  end
  scope :customer_name_like, -> (customer_name) { where('customer_name LIKE ?', "%#{customer_name}%") if customer_name.present? }
  scope :reception_day_from, -> (from) { where('? <= reception_day', from) if from.present? }
  scope :reception_day_to, -> (to) { where('reception_day <= ?', to) if to.present? }

  def self.import(file)
    imported_num = 0

    open(file.path, 'r:cp932:utf-8', undef: :replace) do |f|
      csv = CSV.new(f, :headers => :first_row)
      begin
        csv.each do |row|
          next if row.header_row?
          table = Hash[[row.headers, row.fields].transpose]

          repair = find_by(id: table["id"])
          if repair.nil?
            repair = new
          end

          repair.attributes = table.to_hash.slice(*table.to_hash.except(:id).keys)

          if repair.valid?
            repair.save!
            imported_num += 1
          end
        end
      rescue
      end
    end
    imported_num
  end
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  before_action :logged_in_user
  before_action :editor_or_admin_user, only: %i(edit update update_progress update_contacted update_delivery update_reminder)
  before_action :admin_user, only: %i(data_management destroy import delete_check update_delete_check delete_confirmation delete_all)
  before_action :set_repair, only: %i(show show_sub edit update destroy edit_progress update_progress edit_contacted update_contacted update_delivery update_reminder)
  before_action :repair_with_dele_flag, only: %i(update_delete_check delete_confirmation delete_all reset_delete_check)
  before_action :all_machine_category, only: %i(new create edit update)

  UPDATE_ERROR_MSG = "エラー：データ更新がされませんでした。やり直してください。"

  def index
    # 検索フォームの入力値を取り出す
    # hash = ActiveSupport::HashWithIndifferentAccess.new(search: params[:search])
    # @search_hash = hash[:search]
    @search_params = reception_day_search_params

    if @search_params[:customer_name] == "" && @search_params[:reception_day_from] == "" && @search_params[:reception_day_to] == ""
      redirect_to repairs_url
      flash[:danger] = "検索ワードが入力されていません。"
    else
      @repairs_all = Repair.all
      @repairs = Repair.paginate(page: params[:page], per_page: 20).search(@search_params).
                        order(reminder: :DESC, delivery: :ASC, contacted: :ASC, progress: :ASC, reception_day: :DESC, created_at: :DESC)
      unless @search_params.blank?
        flash.now[:success] = "検索結果:&nbsp;#{@repairs.count}件&emsp;
                                             #{@search_params[:customer_name]}&emsp;
                                             #{(@search_params[:reception_day_from].to_date)&.strftime("%Y年%-m月%-d日")}
                                             #{from_to_text(@search_params[:reception_day_from], @search_params[:reception_day_to])}
                                             #{(@search_params[:reception_day_to].to_date)&.strftime("%Y年%-m月%-d日")}"
      end
    end

    # CSV.PDF出力
    respond_to do |format|
      format.html
      format.csv do
        if current_user.admin? # 管理者のみCVS出力可
          send_data render_to_string.encode(Encoding::Windows_31J, undef: :replace, row_sep: "\r\n", force_quotes: true),
          filename: "修理一覧(#{DateTime.current&.strftime("%Y年%-m月%-d日%-H時%-M分現在")}).csv", type: :csv
        else
          redirect_to repairs_url
        end
      end
      format.pdf do
        @repairs_pdf = Repair.search(@search_params).order(reception_day: :ASC)
        pdf = RepairPDF.new(@repairs_pdf)

        # disposition: "inline" によりPDFはダウンロードではなく画面に表示される
        send_data pdf.render,
          filename:    "修理一覧.pdf",
          type:        "application/pdf",
          disposition: "inline"
      end
    end
  end

  def new
    @repair = Repair.new
    @progress_edit = false
  end

  def create
    @repair = Repair.new(repair_params)
    if @repair.save
      flash[:success] = "#{@repair.customer_name}：修理受付"
      redirect_to repairs_url
    else
      render :new
    end
  end

  def show
    @url = show_sub_repair_url
  end

  def show_sub
  end

  def edit
    @progress_edit = true
  end

  def update
    @progress_edit = true
    if @repair.update_attributes(repair_params)
      flash[:success] = "#{@repair.customer_name}の情報を更新しました。"
      redirect_to repairs_url
    else
      render :edit
    end
  end

  def destroy
    @repair.destroy
    flash[:danger] = "#{@repair.customer_name}の情報を削除しました。"
    redirect_to repairs_url
  end

  def edit_progress
    @users = User.where(admin: false).order(id: :ASC)
  end

  def update_progress
    if @repair.update_attributes(repair_completed_params)
      if @repair.progress == 2
        @repair.completed = nil
        @repair.save
        flash[:primary] = "#{@repair.customer_name}：修理中"
      elsif @repair.progress == 3
        flash[:success] = "#{@repair.customer_name}：修理完了"
      elsif @repair.progress == 1
        @repair.completed = nil
        @repair.save
        flash[:warning] = "#{@repair.customer_name}：進捗情報を解除しました。"
      else
        flash[:success] = "#{@repair.customer_name}：進捗情報を更新しました。"
      end
      redirect_to repairs_url
    else
      if @repair.delivery == 2 && @repair.progress == 1
        flash[:danger] = "引渡済の状態で未完了には更新できません。先に引渡済を解除してください。"
      elsif @repair.delivery == 2 && @repair.progress == 2
        flash[:danger] = "引渡済の状態で修理中には更新できません。先に引渡済を解除してください。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
      redirect_to repairs_url
    end
  end

  def edit_contacted
  end

  def update_contacted
    if @repair.contacted == 1
      if @repair.update_attributes(contacted: 2)
        flash[:success] = "#{@repair.customer_name}：連絡済"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @repair.contacted == 2
      if @repair.update_attributes(contacted: 1)
        flash[:warning] = "#{@repair.customer_name}：連絡済を解除しました。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to repairs_url
  end

  def update_delivery
    if @repair.delivery == 1
      if @repair.update_attributes(delivery: 2, reminder: 1)
        flash[:success] = "#{@repair.customer_name}：引渡し済"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @repair.delivery == 2
      if @repair.update_attributes(delivery: 1)
        flash[:warning] = "#{@repair.customer_name}：引渡し済を解除しました。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to repairs_url
  end

  def update_reminder
    if @repair.reminder == 1
      if @repair.update_attributes(reminder: 2)
        flash[:success] = "#{@repair.customer_name}：催促有り"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @repair.reminder == 2
      if @repair.update_attributes(reminder: 1)
        flash[:warning] = "#{@repair.customer_name}：催促解除"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to repairs_url
  end

  def export
    @reception_year = Repair.all.order(reception_day: :DESC).group_by { |ry| ry.reception_day.strftime("%Y") }
    @reception_month = Repair.all.order(reception_day: :DESC).group_by { |rm| rm.reception_day.strftime("%Y%m") }
  end

  def export_pdf
    @params_date = params[:date]
    @reception_year = Repair.all.order(reception_day: :ASC).group_by { |ry| ry.reception_day.strftime("%Y") }
    @reception_month = Repair.all.order(reception_day: :ASC).group_by { |rm| rm.reception_day.strftime("%Y%m") }
    respond_to do |format|
      format.html
      format.pdf do
        # @repairs_pdf = Repair.search(@search_params).order(reception_day: :ASC)
        @date = @params_date
        @year_pdf = @reception_year
        @month_pdf = @reception_month
        pdf = RepairPDF.new(@year_pdf, @month_pdf, @date)

        # disposition: "inline" によりPDFはダウンロードではなく画面に表示される
        send_data pdf.render,
          filename:    "修理一覧.pdf",
          type:        "application/pdf",
          disposition: "inline"
      end
    end
  end

  def data_management
  end

  def import
    if params[:repairs_file].blank?
      flash[:danger] = "インポートするCSVファイルを選択してください。"
      redirect_to data_management_repairs_url
    else
      num = Repair.import(params[:repairs_file])
      if num > 0
        flash[:success] = "#{num.to_s}件の情報を追加/更新しました。"
        redirect_to repairs_url
      else
        flash[:danger] = "読み込みエラーが発生しました。フォーマットを確認してください。"
        redirect_to data_management_repairs_url
      end
    end
  end

  def delete_check
    @repairs = Repair.all.order(reception_day: :ASC)
  end

  def update_delete_check
    delete_check_params.each do |id, item|
      repair = Repair.find(id)
      repair.update_attributes!(item)
      @last_reception_day = @delete_flag_repairs.maximum(:reception_day)&.to_date
    end
    if Repair.where(delete_check: 1).present? && @last_reception_day <= Date.current << 6
      flash[:warning] = "以下のデータが選択されました。よろしければ削除してください。<br>
                         削除しない場合は【リセット】を押してください。選択を修正する場合は【前画面に戻る】を押してください。".html_safe
      redirect_to delete_confirmation_repairs_url
    elsif Repair.where(delete_check: 1).present? && @last_reception_day >= Date.current << 6
      flash[:warning] = "以下のデータが選択されました。よろしければ削除してください。<br>
                         削除しない場合は【リセット】を押してください。選択を修正する場合は【前画面に戻る】を押してください。<br>
                         注意：6ヶ月以内の受付データが含まれています。".html_safe
      redirect_to delete_confirmation_repairs_url
    else
      flash[:danger] = "削除するデータを選択してください。"
      redirect_to delete_check_repairs_path
    end
  end

  def delete_confirmation
    if @delete_flag_repairs.blank?
      redirect_to root_url
    end
  end

  def delete_all
    delete_count = @delete_flag_repairs.count
    @delete_flag_repairs.each { |repair| repair.destroy }
    flash[:danger] = "#{delete_count}件の修理データを削除しました。"
    redirect_to repairs_url
  end

  def reset_delete_check
    @delete_flag_repairs.each do |repair|
      repair.update_attributes!(delete_check: 0)
    end
    flash[:success] = "削除の選択を取り消しました。データは削除されていません。"
    redirect_to delete_check_repairs_url
  end

  private

    def repair_params
      params.require(:repair).permit(:reception_day,
                                     :customer_name,
                                     :address,
                                     :phone_number,
                                     :mobile_phone_number,
                                     :machine_model,
                                     :condition,
                                     :category,
                                     :note,
                                     :reception_number,
                                     :progress,
                                     :contacted,
                                     :delivery,
                                     :reminder)
    end

    # 修理進捗更新
    def repair_completed_params
      params.require(:repair).permit(:progress, :repair_staff, :completed)
    end

app/helpers/repairs_helper.rb
module RepairsHelper

  # 未進捗件数
  def no_progress_count
    Repair.where(progress: 1).count.to_i
  end

  # 修理中件数
  def in_progress_count
    Repair.where(progress: 2).count.to_i
  end

  # 修理済で未引渡し件数
  def no_delivery_count
    Repair.where(progress: 3).where(delivery: 1).count.to_i
  end

  # 受付番号表示
  def format_reception_number(integer)
    if integer.present?
      format('%06d', integer.to_i)
    end
  end

  # 進捗状況表示
  def progress_text(progress)
    if progress == 1
      "未"
    elsif progress == 2
      "修理中"
    elsif progress == 3
      "✔"
    else
      "未登録"
    end
  end

  def item_text(item)
    if item == 1
      "未"
    elsif item == 2
      "✔"
    else
      "未登録"
    end
  end

  # 催促表示
  def reminder_text(reminder)
    if reminder == 1
      "―"
    elsif reminder == 2
      "✔"
    else
      "未登録"
    end
  end

  # 修理完了日表示 date_fieldにて完了日が空の場合は今日の日付を表示する
  def date_text(completed_day)
    if completed_day.blank?
      Date.today
    else
      completed_day.to_date
    end
  end

  # 完了した項目に「済」を表示
  def sumi_text(complete)
    if complete == 2
      "済"
    end
  end

  # 範囲検索結果flashメッセージの"～"の表示
  def from_to_text(from, to)
    if from.present? || to.present?
      "～"
    end
  end

  # pdf出力ボタン文字均等割付(文字数2の場合は両端に半角スペース挿入)
  def pdf_link_text(text)
    if text.length == 2
      "&nbsp;#{text}&nbsp;".html_safe
    else
      text
    end
  end

  # 年の表示
  def year_text(text, format)
    (text + "0101").to_date&.strftime(format)
  end

  # 月の表示
  def month_text(text, format)
    (text + "01").to_date&.strftime(format)
  end

  # 編集権限あり
  def edit_authority
    current_user.editor? || current_user.admin?
  end

  # 編集権限なし
  def edit_no_authority
    !current_user.editor? || !current_user.admin?
  end
end

app/views/repairs/data_management.html.erb
<% provide(:title, "データ管理") %>
<% provide(:btn_export, "CSV出力") %>
<% provide(:btn_import, "CSV読込") %>
<h1>データ管理</h1>
<div class="data-group center">
  <div class="export_list">
    <div class="export_menu">
      <h5 class="data_title">ユーザー</h5>
      <h6>export</h6>
      <div>
        <%= link_to text_space(yield(:btn_export)), users_path(format: :csv), class: "btn btn-lg rounded-pill btn-primary"%>
      </div>
    </div>
    <div class="export_menu">
      <h5 class="data_title">製品カテゴリ</h5>
      <h6>export</h6>
      <div>
        <%= link_to text_space(yield(:btn_export)), machine_categories_path(format: :csv), class: "btn btn-lg rounded-pill btn-success"%>
      </div>
    </div>
    <div class="export_menu">
      <h5 class="data_title">修理</h5>
      <h6>export</h6>
      <div>
        <%= link_to text_space(yield(:btn_export)), repairs_path(format: :csv), class: "btn btn-lg rounded-pill btn-danger"%>
      </div>
    </div>
  </div>

  <div class="inport_list">
    <div class="inport_menu">
      <h6>import</h6> <!-- ユーザー -->
      <div>
        <%= form_with url: import_users_path, local: true do |f| %>
          <%= f.label :users_file, "ファイル選択", class: "btn btn-lg rounded-pill btn-outline-primary" %>
          <%= f.file_field :users_file, class: "csv_inport_form" %>
          <div><%= f.submit text_space(yield(:btn_import)), class: "btn btn-lg rounded-pill btn-primary" %></div>
        <% end %>
      </div>
    </div>
    <div class="inport_menu">
      <h6>import</h6> <!-- 製品カテゴリ -->
      <div>
        <%= form_with url: import_machine_categories_path, local: true do |f| %>
          <%= f.label :machine_categories_file, "ファイル選択", class: "btn btn-lg rounded-pill btn-outline-success" %>
          <%= f.file_field :machine_categories_file, class: "csv_inport_form" %>
          <div><%= f.submit text_space(yield(:btn_import)), class: "btn btn-lg rounded-pill btn-success" %></div>
        <% end %>
      </div>
    </div>
    <div class="inport_menu">
      <h6>import</h6> <!-- 修理 -->
      <div>
        <%= form_with url: import_repairs_path, local: true do |f| %>
          <%= f.label :repairs_file, "ファイル選択", class: "btn btn-lg rounded-pill btn-outline-danger" %>
          <%= f.file_field :repairs_file, class: "csv_inport_form" %>
          <div><%= f.submit text_space(yield(:btn_import)), class: "btn btn-lg rounded-pill btn-danger" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/repairs/delete_confirmation.html.erb
<% provide(:title, "まとめて削除") %>
<div>
  <h1>まとめて削除</h1>
  <div class="delete_check_form">
    <div class="delete_check_btn">
      <%= form_with(model: @repair, url: delete_all_repairs_path, local: true, method: :delete) do |f| %>
      <%= f.submit text_space("削除"), data: { confirm: "#{@delete_flag_repairs.count}件のデータを削除します。",
          cancel: "キャンセル", commit: "削除"}, title: "削除の確認", class: "btn btn-danger" %>
      <% end %>
    </div>
    <div class="delete_check_btn">
      <%= form_with(model: @repair, url: reset_delete_check_repairs_path, local: true, method: :patch) do |f| %>
        <%= f.submit "リセット", class: "btn btn-outline-primary" %>
      <% end %>
    </div>
    <div class="delete_check_btn">
      <%= link_to "前画面に戻る", delete_check_repairs_path, class: "btn btn-outline-secondary" %>
    </div>
  </div>
  <table class="table table-bordered table-condensed table-hover">
    <thead class="thead-light center">
      <tr>
        <th><%= Repair.human_attribute_name :reception_day %></th>
        <th><%= Repair.human_attribute_name :reception_number %></th>
        <th><%= Repair.human_attribute_name :customer_name %></th>
        <th><%= Repair.human_attribute_name :machine_model %></th>
        <th><%= Repair.human_attribute_name :progress %></th>
        <th><%= Repair.human_attribute_name :contacted %></th>
        <th><%= Repair.human_attribute_name :delivery %></th>
        <th><%= Repair.human_attribute_name :reminder %></th>
      </tr>
    </thead>
    <tbody class="center">
      <% @delete_flag_repairs.each do |r| %>
      <% if r.reception_day.to_date >= Date.current << 6 %>
        <tr bgcolor="<%= "#fff3cd" %>">
      <% else %>
        <tr>
      <% end %>
          <td><%= r.reception_day.strftime("%Y/%-m/%-d") %></td>
          <td><%= blank_text(format_reception_number(r.reception_number)) %></td>
          <td><%= r.customer_name %></td>
          <td><%= r.machine_model %></td>
          <td><%= progress_text(r.progress) %></td>
          <td><%= progress_text(r.contacted) %></td>
          <td><%= progress_text(r.delivery) %></td>
          <td><%= reminder_text(r.reminder) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/repairs/index.html.erb
<% provide(:title, "一覧") %>
<h1>修理一覧</h1>
<h4>
  <% if no_progress_count > 0 %>
    <span class="badge badge-pill badge-danger">未着手&nbsp;<%= no_progress_count %>件</span>
  <% end %>
  <% if in_progress_count > 0 %>
    <span class="badge badge-pill badge-primary">修理中&nbsp;<%= in_progress_count %>件</span>
  <% end %>
  <% if no_delivery_count > 0 %>
    <span class="badge badge-pill badge-success">引渡待ち&nbsp;<%= no_delivery_count %>件</span>
  <% end %>
</h4>
<div class="row justify-content-md-center">
  <div class="col-md-12">
    <div class="input-menu">
      <%= link_to "修理登録", new_repair_path, class: "btn btn-primary btn-repair--new" %>
      <%= form_with(scope: :search, url: repairs_path, method: :get, local: true) do |f| %>
        <div class="col-md-10 input-group">
          <%= f.text_field :customer_name, value: @search_params[:customer_name], placeholder: '得意先名', class: "form-control" %>
          &nbsp;
          <%= f.date_field :reception_day_from, value: @search_params[:reception_day_from], class: "form-control" %>
          ～
          <%= f.date_field :reception_day_to, value: @search_params[:reception_day_to], class: "form-control" %>
          <div class="input-group-append">
            <%= f.submit '検索', name: nil, class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
      <% if params[:search].present? %>
        <%= link_to "リセット", repairs_path, class: "btn btn-outline-secondary btn-repair--new" %>
      <% end %>
    </div>

    <%= will_paginate @users, previous_label: '<', next_label: '>', inner_window: 1 %>
    <table class="table table-bordered table-condensed table-hover">
      <thead class="thead-light center">
        <tr>
          <th><%= Repair.human_attribute_name :reception_day %></th>
          <th><%= Repair.human_attribute_name :reception_number %></th>
          <th><%= Repair.human_attribute_name :customer_name %></th>
          <th><%= Repair.human_attribute_name :machine_model %></th>
          <th><%= Repair.human_attribute_name :progress %></th>
          <th><%= Repair.human_attribute_name :contacted %></th>
          <th><%= Repair.human_attribute_name :delivery %></th>
          <th><%= Repair.human_attribute_name :reminder %></th>
          <% if edit_authority %>
            <th></th>
          <% end %>
          <% if current_user.admin? && !current_user?(@user) %>
            <th></th>
          <% end %>
        </tr>
      </thead>
      <tbody class="center">
        <% @repairs.each do |r| %>
          <% if r.reminder == 2 %>
            <tr bgcolor="<%= "#FFCCCC" %>">
          <% elsif r.delivery == 2 %>
            <tr bgcolor="<%= "#e2e4eb" %>">
          <% elsif r.progress == 3 && r.delivery == 1 %>
            <tr bgcolor="<%= "#F4F4F4" %>">
          <% else %>
            <tr>
          <% end %>
          <td>
            <%= r.reception_day.strftime("%-m/%-d") %>
            (<%= $days_of_the_week[r.reception_day.wday] %>)
          </td>
          <td><%= blank_text(format_reception_number(r.reception_number)) %></td>
          <td>
            <%= link_to r.customer_name, repair_path(r), remote: true %>
            <% if r.created_at.since(1.day) > Time.now %>
              <span class="badge badge-pill badge-info badge-new">
                new
              </span>
            <% end %>
            <% if r.updated_at.since(2.minutes) > Time.now %>
              <span class="badge badge-pill badge-info badge-update">
                update
              </span>
            <% end %>
          </td>
          <td><%= r.machine_model %></td>
          <td>
            <% if r.progress == 1 && edit_authority %>
              <%= link_to progress_text(r.progress), edit_progress_repair_path(r), remote: true, class: "btn btn-sm btn-outline-secondary" %>
            <% elsif r.progress == 2 && edit_authority %>
              <%= link_to progress_text(r.progress), edit_progress_repair_path(r), remote: true, class: "btn btn-sm btn-outline-primary" %>
            <% elsif r.progress == 3 && edit_authority %>
              <%= link_to progress_text(r.progress), edit_progress_repair_path(r), remote: true, class: "repair_check" %>
            <% else %>
              <%= progress_text(r.progress) %>
            <% end %>
          </td>
          <td>
            <% if r.contacted == 1 && r.progress == 3 && edit_authority %>
              <%= link_to item_text(r.contacted), update_contacted_repair_path(r), method: :patch, class: "btn btn-sm btn-outline-secondary" %>
            <% elsif r.contacted == 2 && edit_authority %>
              <%= link_to item_text(r.contacted), update_contacted_repair_path(r), method: :patch, class: "repair_check" %>
            <% else %>
              <%= item_text(r.contacted) %>
            <% end %>
          </td>
          <td>
            <% if r.delivery == 1 && r.progress == 3 && edit_authority %>
              <%= link_to item_text(r.delivery), update_delivery_repair_path(r), method: :patch, class: "btn btn-sm btn-outline-secondary" %>
            <% elsif r.delivery == 2 && edit_authority %>
              <%= link_to item_text(r.delivery), update_delivery_repair_path(r), method: :patch, class: "repair_check" %>
            <% else %>
              <%= item_text(r.delivery) %>
            <% end %>
          </td>
          <td>
            <% if r.delivery == 1 && r.reminder == 1 && edit_authority %>
              <%= link_to reminder_text(r.reminder), update_reminder_repair_path(r), method: :patch %>
            <% elsif r.delivery == 1 && r.reminder == 2 && edit_authority %>
              <%= link_to reminder_text(r.reminder), update_reminder_repair_path(r), method: :patch, class: "reminder_check"%>
            <% elsif r.delivery == 2 && r.reminder == 1 || edit_no_authority %>
              <%= reminder_text(r.reminder) %>
            <% end %>
          </td>
          <% if edit_authority %>
            <td>
              <%= link_to "修正", edit_repair_path(r), class: "btn btn-sm btn-success" %>
            </td>
          <% end %>
          <% if current_user.admin? && !current_user?(@user) %>
            <td>
              <%= link_to "削除", r, method: :delete, data: { confirm: "#{r.customer_name}のデータを削除します。",
                  cancel: "キャンセル", commit: "削除"}, title: "削除の確認", class: "btn btn-sm btn-danger"%>
            </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @users, previous_label: '<', next_label: '>', inner_window: 1 %>
  </div>
</div>

<!-- モーダル -->
<div id="show" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit_progress" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>