config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      patch 'editor_switch' # 編集権限切替
    end
    collection do
      post 'import'
    end
  end
  resources :repairs do
    member do
      get 'show_sub'
      get 'edit_progress' # 進捗チェック
      patch 'update_progress'
      patch 'update_contacted' # 連絡チェック
      patch 'update_delivery' # 引渡チェック
      patch 'update_reminder' # 催促チェック
    end
    collection do
      get 'export'
      get 'export_pdf'
      get 'data_management'
      post 'import'
      get 'delete_check' # まとめて削除チェック
      patch 'update_delete_check' # まとめて削除チェック更新
      get 'delete_confirmation' # まとめて削除確認
      delete 'delete_all' # まとめて削除
      patch 'reset_delete_check' # 削除選択のリセット
    end
  end
  resources :machine_categories, except: :show do
    collection do
      post 'import'
    end
  end
end

app/views/layouts/_header.html.erb
<% if Rails.env.development? %>
  <% provide(:header_title, "修理管理票 development") %>
<% end %>
<% if Rails.env.production? %>
  <% provide(:header_title, "修理管理票") %>
<% end %>

<% if Rails.env.development? %>
  <header class="navbar navbar-expa navbar-default fixed-top">
<% end %>
<% if Rails.env.production? %>
  <header class="navbar navbar-expa navbar-dark bg-dark fixed-top">
<% end %>
  <div class="container">
    <%= link_to "#{yield(:header_title)}", root_path, id: "logo" %>
    <div class="header-list">
      <ul>
        <% if logged_in? %>
          <li>
            <%= link_to "修理一覧", repairs_path, id: "header-menu" %>
          </li>
          <li class="dropdown">
            <%= link_to "PDF出力", export_repairs_path, id: "header-menu" %>
          </li>
          <% if current_user.admin? %>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#" id="header-menu" role="button" data-toggle="dropdown">
                  データ管理
              </a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li class="dropdown-item">
                  <%= link_to "ユーザー登録/編集", users_path, id: "header-menu" %>
                </li>
                <li class="dropdown-item">
                  <%= link_to "製品カテゴリ登録/編集", machine_categories_path, id: "header-menu" %>
                </li>
                <li class="dropdown-item">
                  <%= link_to "データ入出力", data_management_repairs_path, id: "header-menu" if current_user.admin? %>
                </li>
                <li class="dropdown-item">
                  <%= link_to "まとめて削除", delete_check_repairs_path, id: "header-menu" if current_user.admin? %>
                </li>
              </ul>
            </li>
          <% end %>
          <li class="dropdown">
            <a class="dropdown-toggle" href="#" id="header-menu" role="button" data-toggle="dropdown">
                <%= current_user.name %>
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item">
                <%= link_to "ユーザー情報", user_path(current_user), id: "header-menu" %>
              </li>
              <li class="dropdown-item">
                <%= link_to "ログアウト", logout_path, method: :delete, id: "header-menu"%>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- aktmac-app ver1.0 -->
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag('favicon.ico') %>
    <%= favicon_link_tag('apple-touch-icon.png', {:rel => 'apple-touch-icon', :sizes => '180*180', :type => 'image/png'}) %>
    <%= favicon_link_tag('android-touch-icon.png', {:rel => 'android-touch-icon', :sizes => '192*192', :type => 'image/png'}) %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, msg| %>
          <div class="alert alert-<%= message_type %>">
            <%= msg.html_safe %>
          </div>
        <% end  %>
      </div>
    </header>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>